[tool.poetry]
name = "face-characters-detection"
version = "0.1.0"
description = ""
authors = ["Vetrichelvan"]
readme = "README.md"
packages = [{include = "face_characters_detection"}]

[tool.poetry.dependencies]
python = "3.9.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
